[package]
name = "rusty_vector"
version = "0.0.0"
edition = "2021"

[lib]
name = "rusty_vector"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
simsimd = "5.0.0"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "basic"
harness = false
